eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost
server:
    port: 9000
    forward-headers-strategy: framework
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedHeaders: "*"
                        allowedMethods: "*"
                        allowedOrigins: "*"
            routes:

            -   id: PATIENT-SERVICE
                predicates:
                - Path=/patient/**
                uri: lb://PATIENT-SERVICE
                
            -   id: DOCTOR-SERVICE
                predicates:
                - Path=/doctor/**
                uri: lb://DOCTOR-SERVICE
                
            -   id: ADMIN-SERVICE
                predicates:
                - Path=/admin/**
                uri: lb://ADMIN-SERVICE
                
            -   id: RECEPTION-SERVICE
                predicates:
                - Path=/reception/**
                uri: lb://RECEPTION-SERVICE